version: '3.8'
services:
  workspace:
    build: 
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - ../..:/workspaces:cached
    command: sleep infinity