volumes:
  ollama_storage:

x-ollama: &service-ollama
  image: ollama/ollama:rocm
  container_name: ollama
  deploy:
    resources:
      reservations:
        devices:
        - driver: nvidia
          capabilities: ["gpu"]
          count: all
  volumes:
    - ollama_storage:/root/.ollama
  restart: always
  ports:
    - 11434:11434

x-init-ollama: &init-ollama
  image: ollama/ollama:rocm
  container_name: ollama-pull-llm
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  environment:
    - OLLAMA_HOST=ollama:11434
  command:
    - "-c"
    - "sleep 3; ollama pull mistral-small3.1; ollama pull gemma3:4b-it-q4_K_M;"

services:

  ollama-gpu:
    <<: *service-ollama

  ollama:
    <<: *init-ollama
    depends_on:
      - ollama-gpu
